test:
  image: python:3.7

  variables:
    CONFIG: 'gitlab'

  script:
    - apt-get update -qy
    - apt-get install -qy python-dev python-pip
    - pip install pip-tools
    - chmod 700 requirements/update.sh
    - ./requirements/update.sh update
    - coverage run --source='.' -m unittest
    - coverage report -m --skip-covered
